### ISSUE TITLE
Changing app parameters

### ISSUE THREAD

**Issue by rzdev** [keetonian/cw-logs-to-slack#2]
Sorry, i'm new to Lambda, i have a question is it possible to change the app parameters once we deployed the app?

**Comment by clauz** [comment]
Yes, it is possible indeed. Which one do you want to change? I will do my best to guide you. I deployed the app myself and changed params after the fact ;)

**Comment by rzdev** [comment]
@clauz i want to change to Log Group, thanks for the help :)

**Comment by clauz** [comment]
Ok, Try the following:

1. Go to AWS lamdba functions
2. Find a function called serverlessrepo-cw-logs-to-slack-cwlog-LogsToLambda-.... and click on it
3. The first section you see is Designer. You should see the name of the function and also another box that says Cloudwatch logs and the below add Trigger button. Below that you should see the log you chose with the a button to delete or a switch to disable it. Go ahead and delete or disable.
4. Use the Add Trigger button a new page opens up. Select as trigger Cloudwatch logs and then you will se more fields to fill out which are the name and the filter pattern. When you are done hit ADD and you will have replaced the trigger log. 

Let me know if you were able to do this! Hope it helps!

**Comment by rzdev** [comment]
@clauz it's working, thank you for your help!
