### ISSUE TITLE
Multiple logs?

### ISSUE THREAD

**Issue by clauz** [keetonian/cw-logs-to-slack#3]
Is there a possibility to define multiple log streams for the notifications. I do not mind if all notifications go into the same channel (I saw a fork related to notifications into multiple channels) but I would love to be able to get notified about errors in multiple logs.

**Comment by keetonian** [comment]
It should be pretty easy to spin up multiple lambdas for this, one for each channel. I'll look sometime into if it makes sense to do multiple logs into one lambda; maybe with some aggregation it would work well.

**Comment by clauz** [comment]
Thank you!
